# .travis.yml
language: node_js
node_js:
  - "20" # "stable" is fine too; 20 is current LTS on Travis images

branches:
  only:
    - main # or master if that's your default

cache:
  directories:
    - node_modules

install:
  - npm ci || npm i
  - npm install -g yarn

script:
  # - yarn lint        # (kept as a comment like in the lab)
  - yarn build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in Travis repo settings (env var)
  local_dir: build
  target_branch: gh-pages
  on:
    branch: main # or master
