language: node_js
node_js:
  - "20"

branches:
  only:
    - main # <- use master if that's your default

cache:
  npm: true

install:
  - npm ci || npm i

# (Safety) strip any stray NULLs from description before build
before_script:
  - node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json','utf8'));p.description=(p.description||'').replace(/\u0000/g,'');fs.writeFileSync('package.json',JSON.stringify(p,null,2));"

script:
  - npm run build
  - cp build/index.html build/404.html # <-- use cp, not mv

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh-pages
  on:
    branch: main
