language: node_js
node_js:
  - "20"

cache:
  npm: true

install:
  - npm ci || npm i

script:
  - npm run build

before_deploy:
  - echo "Build contents:" && ls -la build

deploy:
  provider: pages
  strategy: git
  token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh-pages # publish into gh-pages branch
  keep_history: true
  on:
    branch: main # <— deploy when MAIN updates
